// Auto-generated by generate-rbac-paths CLI tool
// Do not edit manually - regenerate with: pnpm generate:rbac-paths

export const MODULE_USER_PATHS = {
  "035fe8a6-d467-40c0-9d1d-6a87f0dd286e": [],
  "f9e77c8f-bfd1-4fd4-80b0-e1d891ab7113": [],
  "025fdd23-2803-4360-9fd9-eaa3612c2e23": [],
  "9259d704-c670-4e77-a3a1-a728ffc5be3d": [],
  "9f6416e6-7b9b-4e1a-a99f-833191eca8a9": [],
  "db41ba46-e171-4324-8845-99353eba8568": [],
  "04cfc677-0fd2-4f5e-adf4-2483a00c0277": [],
  "6f975207-0df3-4c0d-b541-ed5dc04487b2": [],
} as const;

export type ModuleUserPathsType = typeof MODULE_USER_PATHS;
